services:
  nginx-keycloak:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: ws-keycloak-nginx
    container_name: ws-keycloak-nginx
    depends_on:
      - ws-keycloak-app
      - postgres
    ports:
      - "443:443"

  postgres:
    image: postgres:15.4
    container_name: ws-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - wspgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ws-keycloak-app:
    build:
      context: .
      dockerfile: docker/keycloak/Dockerfile
    image: ws-keycloak
    container_name: ws-keycloak
    environment:
      KC_HOSTNAME_URL: https://ws-keycloak.local
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_TRANSACTION_XA_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_FRONTEND_URL: https://ws-keycloak.local/auth

      KC_HOSTNAME_ADMIN_URL: https://ws-keycloak.local
      KC_HOSTNAME_PORT: 443
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      PRINT_ENV: true

    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  wspgdata:

